title: Malc's Pentest Journey
description: Offensive Security Write-ups & Learning Roadmap
theme: jekyll-theme-hacker    # Clean & professional (best for portfolios)
show_downloads: false
logo: /assets/profile.png            # (optional) add a small image later

# Optional: make it even nicer
github: [malc0me00]
